Merge tag 'android-14.0.0_r50' into staging/lineage-21.0_merge-android-14.0.0_r50
Android 14.0.0 Release 50 (AP2A.240605.024)

* tag 'android-14.0.0_r50': (36 commits)
  Set the container field of aconfig flags
  Remove unused method to change icon background color
  Drop platform_apis from java_library
  Drop platform_apis from java_library
  Avoid NoSuchMethodError of List.removeLast() on 24Q2
  Drop platform_apis from android_library
  Refactor rain effect
  Add mid layer rain (behind the subject)
  Update weather configs' constructors.
  Add intensity uniform param.
  Removing unused HandlerRunnable
  Add more debug assets
  Add the explicit namespace to toruslib.
  Add logs for when we schedule and unschedule ClockDrawableWrapper
  Fix widget restore for pre-archived apps
  Expose RRO completion signal
  Revert "Fix widget restore for pre-archived apps"
  Update badge for private space
  Fix widget restore for pre-archived apps
  Include shader/texture assets in weather/graphics lib.
  ...

Change-Id: I688244c6a4a95e84b0175fe8fb76350d4cc7a655